---
- name: Cluster update
  hosts: all
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest
      register: dnf_result
      notify:
        - Reboot if needed

    - name: List updated packages
      debug:
        msg: "{{ dnf_result.results }}"
      when: dnf_result.changed

  handlers:
    - name: Reboot if needed
      reboot:
        msg: "Rebooting after package updates"
        connect_timeout: 50
        reboot_timeout: 1200
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: whoami
